"""add_rubric_text_to_scenario

Revision ID: 6bf9686b22bf
Revises: e61650f90cbb
Create Date: 2025-09-13 15:55:59.900051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf9686b22bf'
down_revision = 'e61650f90cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('rubric_text')

    # ### end Alembic commands ###
